name: PHP_Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILDS_TOKEN }}
      - name: Composer Install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Get Changed PHP Files
        id: changed-php-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.php
      - name: Launch Pint inspection
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && steps.changed-php-files.outputs.any_changed == 'true'
        run: vendor/bin/pint --test ${{ steps.changed-php-files.outputs.all_changed_files }}
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
